### ISSUE TITLE
[Bug] Can’t load plugin with different lua module name

### ISSUE THREAD

**Issue by boltlessengineer** [nvim-neorocks/rocks-dev.nvim#26] opened 2024-07-22 15:16 UTC
I’m not sure if this is issue of `rocks-dev.nvim` or `rocks-config.nvim`.

```toml
"rocks.nvim" = "2.36.0"
"rocks-dev.nvim" = "1.2.4"
"rocks-config.nvim" = "2.1.4"
"markdown.nvim" = { dir = "~/repo/markdown.nvim"}
```

I installed [markdown.nvim](https://github.com/MeanderingProgrammer/markdown.nvim) like this and write this lua code on my `lua/plugins/markdown.lua` file.

```lua
require(“render-markdown”).setup({})
```

and I’m facing error from `:checkhealth rocks-config` when I restart neovim:

```
rocks-config: require("rocks-config.health").check()

Checking for errors while loading configs ~
- ERROR Error while loading config 'markdown.lua' for 'markdown.nvim'.
  - ADVICE:
    - Error was: /home/ubuntu/.config/nvim_rocks/lua/plugins/markdown.lua:1: module 'render-markdown' not found:No LuaRocks module found for render-markdown
      	no field package.preload['render-markdown']
      	no file './render-markdown.lua'
      	no file '/home/ubuntu/repo/neovim/.deps/usr/share/luajit-2.1/render-markdown.lua'
      	no file '/usr/local/share/lua/5.1/render-markdown.lua'
      	no file '/usr/local/share/lua/5.1/render-markdown/init.lua'
      	no file '/home/ubuntu/repo/neovim/.deps/usr/share/lua/5.1/render-markdown.lua'
      	no file '/home/ubuntu/repo/neovim/.deps/usr/share/lua/5.1/render-markdown/init.lua'
      	no file '/home/ubuntu/.local/share/nvim_rocks/rocks/share/lua/5.1/render-markdown.lua'
      	no file '/home/ubuntu/.local/share/nvim_rocks/rocks/share/lua/5.1/render-markdown/init.lua'
      	no file '/home/ubuntu/.local/share/nvim_rocks/rocks/share/lua/5.1/init.lua'
      	no file './render-markdown.so'
      	no file '/usr/local/lib/lua/5.1/render-markdown.so'
      	no file '/home/ubuntu/repo/neovim/.deps/usr/lib/lua/5.1/render-markdown.so'
      	no file '/usr/local/lib/lua/5.1/loadall.so'
      	no file '/home/ubuntu/.local/share/nvim_rocks/rocks/lib/lua/5.1/render-markdown.so'
      	no file '/home/ubuntu/.local/share/nvim_rocks/rocks/lib64/lua/5.1/render-markdown.so'

Checking for duplicate configuration files ~
- OK No duplicate configurations found.
```

I don’t get this error when

- I manually run `require(“render-markdown”)` after restarting neovim
- I install [markdown.nvim] with `rocks-git.nvim`
- I remove the `lua/plugins/markdown.lua` file

**Comment by mrcjkb** [comment] 2024-07-22 15:56
Hey :wave: 

This is caused by https://github.com/nvim-neorocks/rocks-dev.nvim/issues/8

Closing as duplicate. I'll see if I can find some time to fix #8 soon. It's been open for too long.

**Closed as completed by mrcjkb** 2024-07-22 15:56 UTC
Labels: duplicate
